-- +migrate Up
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sender_number VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(10, 2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS processing_at TIMESTAMP WITH TIME ZONE;
